
version: 1
disable_existing_loggers: false

handlers:
    console:
        class : logging.StreamHandler
        formatter: brief
        level   : DEBUG
        stream  : ext://sys.stdout

    game:
        class: logging.handlers.RotatingFileHandler
        formatter: game
        filename: log/game.log
        maxBytes: 10485760  # 10 MB
        backupCount: 5
        encoding: utf8
        filters: [game]

    general:
        class : logging.handlers.RotatingFileHandler
        formatter: general
        filename: log/general.log
        maxBytes: 10485760
        backupCount: 5
        encoding: utf8
        filters: [general]

formatters:
    brief:
        format: '[Game: %(game_name)-15s] [%(levelname)-10s] [%(name)-10s] %(message)s'
    game:
        format: '%(game_name)-15s; %(thread)6d; %(threadName)12s; msg: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    general:
        format: 'Game: %(game_name)-15s %(asctime)s %(levelname)-10s %(name)-12s %(thread)6d %(threadName)15s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

filters:
    game:
        (): pycman.core.stat.logging.logger.LogFilter
        type: game
    general:
        (): pycman.core.stat.logging.logger.LogFilter
        type: general

root:
    level: DEBUG
    handlers: [console, general, game]
    propogate: yes

loggers:
    root:
        level: INFO
        handlers: [console, game, general]
        propogate: no